printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Pháp - Việt" "Pháp - Việt" "fr" "vi" > star_phapviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Việt - Hàn" "Việt - Hàn" "vi" "ko" > star_viethan.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Việt - Anh" "Việt - Anh" "vi" "en" > star_vietanh.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Nga - Việt" "Nga - Việt" "ru" "vi" > star_ngaviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Việt - Pháp" "Việt - Pháp" "vi" "fr" > star_vietphap.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Tây Ban Nha - Việt" "Tây Ban Nha - Việt" "es" "vi" > star_tbnviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Việt - Tây Ban Nha" "Việt - Tây Ban Nha" "vi" "es" > star_viettbn.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Na Uy - Việt" "Na Uy - Việt" "no" "vi" > star_nauyviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Việt - Đức" "Việt - Đức" "vi" "de" > star_vietduc.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Trung - Việt" "Trung - Việt" "zh" "vi" > star_trungviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Bồ Đào Nha - Việt" "Bồ Đào Nha - Việt" "pt" "vi" > star_bdnviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Nhật - Việt" "Nhật - Việt" "ja" "vi" > star_nhatviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Đức - Việt" "Đức - Việt" "de" "vi" > star_ducviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Việt - Nga" "Việt - Nga" "vi" "ru" > star_vietnga.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Séc - Việt" "Séc - Việt" "cz" "vi" > star_secviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Việt - Nhật" "Việt - Nhật" "vi" "ja" > star_vietnhat.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Hàn - Việt" "Hàn - Việt" "ko" "vi" > star_hanviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Ý - Việt" "Ý - Việt" "it" "vi" > star_yviet.dfo
printf "Name = %s\nDescription = %s từ dự án Open Vietnamese Dictionary Project (OVDP)\nSource = %s\nTarget = %s \nVersion = 1.0\nOwner/Editor = OVDP\nURL = https://github.com/catusphan/dictionary" "Anh - Việt" "Anh - Việt" "en" "vi" > star_anhviet.dfo