./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/es-vi/star_tbnviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/fr-vi/star_phapviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/vi-en/star_vietanh
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/ru-vi/star_ngaviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/vi-fr/star_vietphap
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/no-vi/star_nauyviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/vi-de/star_vietduc
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/zh-vi/star_trungviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/pt-vi/star_bdnviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/ja-vi/star_nhatviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/de-vi/star_ducviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/vi-ru/star_vietnga
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/cz-vi/star_secviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/it-vi/star_yviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/en-vi/star_anhviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/vi-es/star_viettbn
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/ko-vi/star_hanviet
./bin/stardict2txt.py --cleanup  ./ext-stardict-vi/vi-ja/star_vietnhat
